name: Test and Deploy

on:
  push:
    branches: [ 'master', 'develop' ]
    tags: [ '*' ]
  pull_request:
    branches: [ 'master', 'develop' ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.3, 7.4, 8.0]
    steps:
    - uses: actions/checkout@v2
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{ matrix.php-version }}
    - name: Checkout master fixtures
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      uses: actions/checkout@v2
      with:
        repository: IMSGlobal/caliper-spec
        ref: master
        path: ./caliper-spec
    - name: Checkout develop fixtures
      if: ${{ ! startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master' }}
      uses: actions/checkout@v2
      with:
        repository: IMSGlobal/caliper-spec
        ref: develop
        path: ./caliper-spec
    # can't be done in actions/checkout@v2 as it complains if you checkout outside your workspace
    - name: Move caliper specs to where expected
      run: |
        mv ./caliper-spec ../caliper-spec
    - name: Run unit tests
      run: |
        make test

  # NOTE: not tested. Alteratively could just do a github webhook
  # but then tests are not guaranteed to pass before an update ¯\_(ツ)_/¯
  # deploy_to_packagist:
  #   runs-on: ubuntu-latest
  #   needs: [ unit_tests ]
  #   # only deploy master and tagged releases
  #   if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #   - name: trigger update hook
  #     run: |
  #       curl -X POST \
  #           -H "content-type:application/json" \
  #           -d '{"repository":{"url":"<TODO_PACKAGIST_PACKAGE_URL>"}}' \
  #           https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}

